In [2]:
import torch


In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x[2]

tensor(2)

In [6]:
len(x)

3

In [7]:
x.shape

torch.Size([3])

In [8]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [13]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4) #2个3乘4
print(X)
print(X.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


In [15]:
print(a+X)
print((X+a).shape)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


In [16]:
A.shape, A.sum()#0到5求和

(torch.Size([2, 3]), tensor(15.))

In [17]:
print(A)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [18]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [19]:
A.sum(axis=0)#axis=0,沿着列求和

tensor([3., 5., 7.])

In [20]:
A.sum(axis=0).shape

torch.Size([3])

In [21]:
A.sum(axis=1)#沿着1维（行）求和

tensor([ 3., 12.])

In [22]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [23]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()#行和列都加起来

tensor(True)

In [24]:
A.mean(), A.sum() / A.numel()#取平均

(tensor(2.5000), tensor(2.5000))

In [25]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]#A有三列，求出每列的平均值

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [26]:
sum_A = A.sum(axis=1, keepdims=True)#新的张量等于A延行求和
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [27]:
A / sum_A#第一行除以3，第二行除以12

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [28]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [29]:
y = torch.ones(3, dtype = torch.float32)#y向量长度为3,元素全是1
x, y, torch.dot(x, y)#x,y做点积

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [32]:
z = torch.ones(3,3,dtype = torch.float32)

In [33]:
torch.sum(x * y)

tensor(3.)

In [34]:
A.shape, x.shape, torch.mv(A, x), A@x#矩阵A点乘向量x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [36]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B#矩阵乘法

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [37]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)#向量的模长

tensor(5.)

In [38]:
torch.abs(u).sum()#曼哈顿距离Manhattan

tensor(7.)

In [39]:
torch.norm(torch.ones((4, 9)))#Frobenius norm

tensor(6.)

In [42]:
print(len(A))
print(A)

2
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [44]:
A/A.sum(axis=0)

tensor([[0.0000, 0.2000, 0.2857],
        [1.0000, 0.8000, 0.7143]])

In [46]:
Z = torch.arange(24).reshape(2, 4, 3)
Z

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [51]:
print(Z.sum(axis=0))
print(Z.sum(axis=1))#18=0+3+6+9第一个矩阵的第一列求和，以此类推
print(Z.sum(axis=2))#21=6+7+8第一个矩阵的第三行求和，以此类推

tensor([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]])
tensor([[18, 22, 26],
        [66, 70, 74]])
tensor([[ 3, 12, 21, 30],
        [39, 48, 57, 66]])


In [47]:
Y=torch.arange(24).reshape(3,4,2)
Y

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])

In [50]:
print(Y.sum(axis=0))
print(Y.sum(axis=1))
print(Y.sum(axis=2))

tensor([[24, 27],
        [30, 33],
        [36, 39],
        [42, 45]])
tensor([[12, 16],
        [44, 48],
        [76, 80]])
tensor([[ 1,  5,  9, 13],
        [17, 21, 25, 29],
        [33, 37, 41, 45]])
