In [2]:
import torch
from d2l import torch as d2l

print("PyTorch 版本:", torch.__version__)
print("d2l 导入成功！")

PyTorch 版本: 2.0.0+cpu
d2l 导入成功！


In [3]:
import torch
from d2l import torch as d2l

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [4]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 加法
print(a + b)  # tensor([5, 7, 9])

# 乘法（对应位置相乘）
print(a * b)  # tensor([4, 10, 18])

# 矩阵乘法
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print(torch.mm(A, B))  # 矩阵相乘

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([[19, 22],
        [43, 50]])


In [5]:
x = torch.arange(12, dtype=torch.float32) #data type is float
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

x.numel()

In [6]:
x.shape

torch.Size([12])

In [7]:
X = x.reshape(3, 4)#3 rows multiply 4 columns
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))#there are 2 matrix, 3 multiply 4

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(3, 4)

tensor([[-0.4975, -1.9281,  0.2505, -0.6132],
        [-1.0873, -0.5222,  0.2001, -0.4391],
        [-1.5363, -1.6208, -1.6819, -1.7748]])

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [12]:
X[-1], X[1:3]#-1:the last row
#the first row or column's idex is 0
#[1:3]means the second(1) and the third(2) row

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [13]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[:2] = 12
X#the first(0) row and the second row are equal to 12

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [16]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dim=0 add to vertical
# dim=1 add to level
# cat:split,joint

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [20]:
X.sum()

tensor(66.)

In [38]:
X == Y#logical statements

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
X<Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
X>Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [21]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
a + b
#broadcast

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
print(X)
id(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


2426649769040

In [24]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [41]:
before = id(Y)#store original address
Y = Y + X
print(Y)
id(Y)==before

tensor([[ 4.,  5., 14., 15.],
        [14., 19., 24., 29.],
        [32., 33., 34., 35.]])


False

In [26]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y#method 1: use[:]
print('id(Z):', id(Z))

id(Z): 2426649702544
id(Z): 2426649702544


In [27]:
before = id(X)#id(),keep original address
X += Y#method 2:use +=
id(X) == before
#original address is not changed

True

In [28]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)