In [10]:
import torch
from d2l import torch as d2l

print("PyTorch 版本:", torch.__version__)
print("d2l 导入成功！")

PyTorch 版本: 2.0.0+cpu
d2l 导入成功！


In [11]:
import torch
from d2l import torch as d2l

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [12]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 加法
print(a + b)  # tensor([5, 7, 9])

# 乘法（对应位置相乘）
print(a * b)  # tensor([4, 10, 18])

# 矩阵乘法
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print(torch.mm(A, B))  # 矩阵相乘

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([[19, 22],
        [43, 50]])


In [13]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
x.numel()

12

In [15]:
x.shape

torch.Size([12])

In [18]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [21]:
torch.randn(3, 4)

tensor([[-0.1362,  0.5904,  1.5911, -1.1228],
        [ 0.6467,  1.2072,  0.4229,  0.2251],
        [-1.1644, -1.5421, -1.3977,  0.4201]])

In [22]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])